import { Router, Response } from 'express';
import { requireAuth, AuthenticatedRequest } from '../middleware/auth';
import { AIService } from '../services/aiService';
import { supabase, insertAuditLog } from '../services/supabaseClient';

const router = Router();

// In-memory fallback repository for instant zero-config sandbox previewing
const sandboxPoliciesStore: Record<string, any[]> = {};
const sandboxVersionsStore: Record<string, any[]> = {};


// GET /api/policies - Fetch user's generated policies
router.get('/', requireAuth, async (req: AuthenticatedRequest, res: Response) => {
  const userId = req.userId || 'demo_user';

  if (supabase) {
    const { data, error } = await supabase
      .from('policies')
      .select('*')
      .eq('user_id', userId)
      .order('created_at', { ascending: false });

    if (!error && data) {
      return res.json({ success: true, data });
    }
  }

  const userPolicies = sandboxPoliciesStore[userId] || getInitialDefaultPolicies(userId);
  sandboxPoliciesStore[userId] = userPolicies;
  return res.json({ success: true, data: userPolicies });
});

// POST /api/policies/generate - Trigger AI Policy Generation
router.post('/generate', requireAuth, async (req: AuthenticatedRequest, res: Response) => {
  const userId = req.userId || 'demo_user';
  const { framework, companyName, industry, cloudProvider, dataTypes, teamSize, customRequirements } = req.body;

  try {
    const generated = await AIService.generatePolicy({
      framework: framework || 'SOC 2',
      companyName: companyName || 'SaaS Startup Inc',
      industry: industry || 'FinTech / SaaS',
      cloudProvider: cloudProvider || 'AWS',
      dataTypes: dataTypes || ['Customer Email', 'Authentication Tokens', 'Financial Records'],
      teamSize: teamSize || '1-20',
      customRequirements
    });

    const now = new Date().toISOString();
    const templateVersion = '2.4.0';
    const modelName = process.env.OPENROUTER_API_KEY ? 'meta-llama/llama-3.1-70b-instruct' : 'Arky AI Synthesizer v2.4';

    const newPolicy = {
      id: `pol_${Date.now()}_${Math.random().toString(36).substr(2, 6)}`,
      user_id: userId,
      title: generated.title,
      framework: framework || 'SOC 2',
      category: generated.category,
      content: generated.content,
      version: 1,
      status: 'Published',
      compliance_tags: generated.tags,
      // Required fields from spec
      generated_at: now,
      model_name: modelName,
      template_version: templateVersion,
      // Additional metadata
      model_used: modelName,
      tailoring_cues: { companyName, industry, cloudProvider, dataTypes, teamSize },
      edit_count: 0,
      created_at: now,
      updated_at: now
    };

    // Store initial version snapshot
    const initialVersion = {
      id: `ver_${Date.now()}_0`,
      policy_id: newPolicy.id,
      version: 1,
      content: newPolicy.content,
      model_used: modelName,
      edited_by: userId,
      edited_at: now
    };
    sandboxVersionsStore[newPolicy.id] = [initialVersion];

    if (supabase) {
      const { data, error } = await supabase.from('policies').insert([newPolicy]).select();
      if (!error && data) {
        await supabase.from('policy_versions').insert([initialVersion]);
        // Write audit log
        await insertAuditLog(userId, 'policy_created', 'policy', {
          policy_id: data[0].id,
          framework,
          title: data[0].title,
          model_name: modelName,
        });
        return res.json({ success: true, data: data[0] });
      }
    }

    if (!sandboxPoliciesStore[userId]) {
      sandboxPoliciesStore[userId] = getInitialDefaultPolicies(userId);
    }
    sandboxPoliciesStore[userId].unshift(newPolicy);

    // Write audit log in sandbox mode
    await insertAuditLog(userId, 'policy_created', 'policy', {
      policy_id: newPolicy.id,
      framework,
      title: newPolicy.title,
      model_name: modelName,
    });

    return res.json({ success: true, data: newPolicy, message: 'Policy successfully generated by AI engine' });
  } catch (err: any) {
    return res.status(500).json({ success: false, error: err.message });
  }
});

// PUT /api/policies/:id - Edit an existing policy (bump version & edit_count)
router.put('/:id', requireAuth, async (req: AuthenticatedRequest, res: Response) => {
  const userId = req.userId || 'demo_user';
  const { id } = req.params;
  const { content, title, status } = req.body;

  if (!content || typeof content !== 'string') {
    return res.status(400).json({ success: false, error: 'Policy content is required for editing' });
  }

  const now = new Date().toISOString();
  let updatedPolicy: any = null;

  // Search sandbox policies store
  if (sandboxPoliciesStore[userId]) {
    const policyIndex = sandboxPoliciesStore[userId].findIndex((p) => p.id === id);
    if (policyIndex !== -1) {
      const existing = sandboxPoliciesStore[userId][policyIndex];
      const newVersion = (existing.version || 1) + 1;
      const newEditCount = (existing.edit_count || 0) + 1;

      updatedPolicy = {
        ...existing,
        title: title || existing.title,
        content: content,
        status: status || existing.status,
        version: newVersion,
        edit_count: newEditCount,
        last_edited_at: now,
        updated_at: now
      };
      sandboxPoliciesStore[userId][policyIndex] = updatedPolicy;

      // Save version snapshot
      if (!sandboxVersionsStore[id]) sandboxVersionsStore[id] = [];
      sandboxVersionsStore[id].unshift({
        id: `ver_${Date.now()}_${newVersion}`,
        policy_id: id,
        version: newVersion,
        content: content,
        model_used: existing.model_used,
        edited_by: userId,
        edited_at: now
      });
    }
  }

  if (supabase) {
    const { data: existing } = await supabase.from('policies').select('*').eq('id', id).single();
    if (existing) {
      const newVersion = (existing.version || 1) + 1;
      const newEditCount = (existing.edit_count || 0) + 1;

      const { data, error } = await supabase
        .from('policies')
        .update({
          content,
          title: title || existing.title,
          status: status || existing.status,
          version: newVersion,
          edit_count: newEditCount,
          last_edited_at: now,
          updated_at: now
        })
        .eq('id', id)
        .select();

      if (!error && data) {
        updatedPolicy = data[0];
        await supabase.from('policy_versions').insert([{
          id: `ver_${Date.now()}_${newVersion}`,
          policy_id: id,
          version: newVersion,
          content,
          model_used: existing.model_used,
          edited_by: userId,
          edited_at: now
        }]);
      }
    }
  }

  if (!updatedPolicy) {
    return res.status(404).json({ success: false, error: 'Policy not found' });
  }

  return res.json({ success: true, data: updatedPolicy, message: 'Policy successfully updated' });
});

// GET /api/policies/:id/versions - Get revision history for a policy
router.get('/:id/versions', requireAuth, async (req: AuthenticatedRequest, res: Response) => {
  const { id } = req.params;

  if (supabase) {
    const { data, error } = await supabase
      .from('policy_versions')
      .select('*')
      .eq('policy_id', id)
      .order('version', { ascending: false });

    if (!error && data && data.length > 0) {
      return res.json({ success: true, data });
    }
  }

  const versions = sandboxVersionsStore[id] || [
    {
      id: `ver_init_${id}`,
      policy_id: id,
      version: 1,
      content: 'Initial generated policy document content.',
      edited_at: new Date(Date.now() - 86400000).toISOString()
    }
  ];

  return res.json({ success: true, data: versions });
});

// Helper for default starter policies
function getInitialDefaultPolicies(userId: string) {
  return [
    {
      id: 'pol_default_01',
      user_id: userId,
      title: 'Information Security & Access Control Policy',
      framework: 'SOC 2',
      category: 'Logical Access Control',
      version: 1,
      status: 'Published',
      compliance_tags: ['SOC 2', 'CC6.1', 'MFA', 'Encryption'],
      model_name: 'Arky AI Synthesizer v2.4',
      model_used: 'Arky AI Synthesizer (v2.4)',
      template_version: '2.4.0',
      generated_at: new Date(Date.now() - 86400000 * 2).toISOString(),
      edit_count: 0,
      content: `# Information Security & Access Control Policy\n\n### 1. Purpose\nEstablishes access rules, encryption standards, and user role management for SOC 2 Type II compliance.\n\n### 2. Controls\n- Mandatory 100% MFA for cloud providers and code repositories.\n- TLS 1.3 encryption in transit and AES-256 at rest.\n- Quarterly user access review audits.`,
      created_at: new Date(Date.now() - 86400000 * 2).toISOString(),
      updated_at: new Date().toISOString()
    },
    {
      id: 'pol_default_02',
      user_id: userId,
      title: 'HIPAA ePHI Security Safeguard & BAA Policy',
      framework: 'HIPAA',
      category: 'Technical Safeguards',
      version: 1,
      status: 'Under Review',
      compliance_tags: ['HIPAA', 'ePHI', 'BAA', 'AES-256'],
      model_name: 'Arky AI Synthesizer v2.4',
      model_used: 'Arky AI Synthesizer (v2.4)',
      template_version: '2.4.0',
      generated_at: new Date(Date.now() - 86400000 * 5).toISOString(),
      edit_count: 0,
      content: `# HIPAA ePHI Security Safeguard Policy\n\n### 1. Mandate\nProtects electronic Protected Health Information across database infrastructure and identity platforms.\n\n### 2. Controls\n- Mandatory Business Associate Agreements (BAAs) with AWS, Supabase, and Clerk.\n- Automatic user logoff after 15 minutes of console inactivity.`,
      created_at: new Date(Date.now() - 86400000 * 5).toISOString(),
      updated_at: new Date().toISOString()
    }
  ];
}


export default router;
